# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kobe I. Calhoun
resume_title:                   "GitHub Scholar"
resume_contact_email:
  "kcalhoun926@gmail.com"
resume_header_contact_info: "Atlanta, Georgia | (404)375-5790 | kcalhoun926@gmail.com"
resume_header_intro: "<p>This is the executive summary. You should be able to find that i'm a leader and not a follower.I'm also a hardworking person that likes to learns new things every day.I also like to help on my on time if you need me to.  "

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       Class of 2020
resume_section_projects:        true
resume_section_skills:          Some skill sets that I have is being a leader and hardworking.
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Kobe Calhoun/resume-template"
  resume_twitter_url:           "http://twitter.com/Thatboy_kobe"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "k.loading1"
  resume_website_url:           "http://Kobe.github.io/resume-template.com
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
